name: XR Simulator Tests

# TEst

on: [push, pull_request]

jobs:
  test:
   runs-on: windows-2019

   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone pyvrs repository
        run: |
          git clone https://github.com/facebookresearch/pyvrs.git
          cd pyvrs
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          cd pyvrs
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r docs/requirements.txt
